name: Install and Tests
on: 
  push: 
    branches:
      - '*'
    tags-ignore:
      - v*.*.*

  pull_request:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*


jobs: 
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: scheduler-test

      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          DB_TEST_URL: ${{ secrets.DB_TEST_URL }}
          CI: true
