name: Install and Tests
on: 
  push: 
    branches:
      - '*'
    tags-ignore:
      - v*.*.*

  pull_request:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*


jobs: 
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          CI: true
